### ISSUE TITLE
Allow Configurable Length For "Description Is A Good Length Check"

### ISSUE THREAD

**Issue by mpchadwick** [mpchadwick/jekyll-pre-commit#7]
Everyone might not agree on this one. Need to think about the best syntax. Maybe...?

```yaml
pre-commit:
  - DescriptionIsGoodLength
    - Min: X
    - Max: Y
```
